services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:4173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    env_file:
      - ./backend/.env
    depends_on: 
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  database:
    image: container-registry.oracle.com/mysql/community-server:latest
    command: --init-file /data/application/init.sql
    volumes:
      - ./db/init.sql:/data/application/init.sql
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]